{
    'name': "KYZN Sales",
    'summary': 'Module Odoo untuk sistem pencatatan sales terpusat KYZN.',
    'description': 'Module Odoo untuk memusatkan pencatatan, validasi, dan pelaporan penjualan membership pada PT Akademi Fambam Indonesia (KYZN).',
    'sequence': -100,
    'author': "Kelompok 06-K03",
    'category': 'Sales',
    'version': '1.0',
    'depends': ['base', 'sale', 'account'],
    'data': [
        'security/kyzn_groups.xml',
        'security/ir.model.access.csv',
        'security/kyzn_record_rules.xml',
        'demo/demo.xml',

        'views/report_graph.xml',
        'views/report_pivot.xml',
        'views/report_search.xml',
        'views/report_tree.xml',
        'views/report_menu.xml',

        'views/sale_order_form.xml',
        'views/sale_order_tree.xml',
        'views/sale_order_search.xml',
        'views/sale_order_menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}